# Generated by Django 6.0.4 on 2026-04-29 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MidiItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(db_index=True, max_length=500, unique=True)),
                ('source_type', models.CharField(choices=[('dataset', 'Dataset'), ('generated', 'Generated')], db_index=True, default='dataset', max_length=20)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Duration in seconds, populated on scan when possible.', null=True)),
                ('file_missing', models.BooleanField(default=False, help_text='True when the file was present previously but is now missing.')),
                ('rating', models.IntegerField(blank=True, help_text='Curator rating 1–10.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('approved', models.BooleanField(blank=True, help_text='null=not reviewed, true=approved, false=rejected.', null=True)),
                ('favorite', models.BooleanField(db_index=True, default=False, help_text='Marked as a favourite.')),
                ('notes', models.TextField(blank=True, help_text='Free-text curator notes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='midi_items', to='midi_curator.tag')),
            ],
            options={
                'ordering': ['source_type', 'name'],
            },
        ),
    ]
