"""Report generator — writes reports/dataset_summary.md from split stats.

Usage::

    python -m tools.analysis.generate_report \\
        --splits-dir data/splits \\
        --output     reports/dataset_summary.md

Or from the build pipeline::

    python -m tools.dataset.build_dataset --input-dir data/raw --report
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

from tools.analysis.stats import compute_all_splits


def _pct(count: int, total: int) -> str:
    if total == 0:
        return "0.0%"
    return f"{100 * count / total:.1f}%"


def _bar_chart(dist: dict[str, int], width: int = 30) -> str:
    """Return a simple ASCII bar chart for a distribution dict."""
    total = sum(dist.values())
    if total == 0:
        return ""
    lines = []
    for label, count in dist.items():
        bar_len = round(count / total * width)
        bar = "█" * bar_len
        lines.append(f"  {label:<20} {bar:<30} {_pct(count, total):>6}  ({count:,})")
    return "\n".join(lines)


def _section(name: str, stats: dict[str, Any]) -> str:
    lines: list[str] = [f"### {name}\n"]

    n_ex = stats.get("n_examples", 0)
    n_tok = stats.get("n_tokens", 0)
    n_src = stats.get("n_sources", 0)
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Examples | {n_ex:,} |")
    lines.append(f"| Tokens (notes) | {n_tok:,} |")
    lines.append(f"| Unique source files | {n_src:,} |")

    if "notes_per_bar_mean" in stats:
        lines.append(
            f"| Notes/bar (mean) | {stats['notes_per_bar_mean']} |"
        )
        lines.append(
            f"| Notes/bar (min/max) | {stats['notes_per_bar_min']} / {stats['notes_per_bar_max']} |"
        )

    if "interval_mean" in stats:
        lines.append(f"| Interval mean (semitones) | {stats['interval_mean']} |")
        lines.append(f"| Interval abs mean | {stats['interval_abs_mean']} |")
        lines.append(f"| Interval std | {stats['interval_std']} |")
        lines.append(f"| Chromatic fraction | {stats['interval_chromatic_fraction']} |")

    if "rhythmic_density_mean" in stats:
        lines.append(f"| Rhythmic density (mean unique 16th positions/example) | {stats['rhythmic_density_mean']} |")

    if "tempo_mean_bpm" in stats:
        lines.append(f"| Tempo mean (BPM) | {stats['tempo_mean_bpm']} |")
        lines.append(f"| Tempo range (BPM) | {stats['tempo_min_bpm']} – {stats['tempo_max_bpm']} |")

    lines.append("")

    if "interval_distribution" in stats:
        lines.append("**Interval distribution** (semitones from chord root)\n")
        lines.append(_bar_chart({k: v for k, v in sorted(stats["interval_distribution"].items(), key=lambda x: int(x[0]))}))
        lines.append("")

    if "dur_bin_distribution" in stats:
        lines.append("**Duration bin distribution**\n")
        lines.append(_bar_chart(stats["dur_bin_distribution"]))
        lines.append("")

    if "vel_bin_distribution" in stats:
        lines.append("**Velocity bin distribution**\n")
        lines.append(_bar_chart(stats["vel_bin_distribution"]))
        lines.append("")

    if "style_distribution" in stats:
        lines.append("**Style distribution**\n")
        lines.append(_bar_chart(stats["style_distribution"]))
        lines.append("")

    if "difficulty_distribution" in stats:
        lines.append("**Difficulty distribution**\n")
        lines.append(_bar_chart(stats["difficulty_distribution"]))
        lines.append("")

    return "\n".join(lines)


def generate_report(splits_dir: Path, output_path: Path) -> None:
    """Generate ``dataset_summary.md`` from split JSONL files."""
    all_stats = compute_all_splits(splits_dir)

    if not all_stats:
        print("No split files found. Run build_dataset.py first.", file=sys.stderr)
        return

    output_path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = [
        "# Dataset Summary\n",
        "> Auto-generated by `tools/analysis/generate_report.py`.\n",
        "## Overview\n",
    ]

    # Combined totals.
    total_ex = sum(s.get("n_examples", 0) for s in all_stats.values())
    total_tok = sum(s.get("n_tokens", 0) for s in all_stats.values())
    lines.append(f"| Split | Examples | Tokens |")
    lines.append(f"|-------|----------|--------|")
    for split_name, stats in all_stats.items():
        lines.append(
            f"| {split_name} | {stats.get('n_examples', 0):,} | {stats.get('n_tokens', 0):,} |"
        )
    lines.append(f"| **Total** | **{total_ex:,}** | **{total_tok:,}** |")
    lines.append("")

    # Per-split detailed sections.
    lines.append("## Per-split statistics\n")
    for split_name, stats in all_stats.items():
        lines.append(_section(split_name.capitalize(), stats))

    output_path.write_text("\n".join(lines), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate dataset_summary.md from split JSONL files.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--splits-dir", type=Path, default=Path("data/splits"),
        help="Directory containing train.jsonl / val.jsonl / test.jsonl.",
    )
    parser.add_argument(
        "--output", type=Path, default=Path("reports/dataset_summary.md"),
        help="Output markdown file.",
    )
    args = parser.parse_args(argv)

    generate_report(args.splits_dir, args.output)
    print(f"Report written to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
